version: '3.7'

services:
  back:
    build: ./
    volumes:
      - .:/usr/src/app/test_case/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  postgres_data: